# Generated by Django 4.0.5 on 2022-06-13 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=400)),
                ('created_gs', models.DateTimeField(auto_now=True)),
                ('updated_gs', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoney.customers')),
            ],
        ),
    ]
