# Generated by Django 3.2.13 on 2022-06-20 23:50

import cmoney.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status_tr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='exchange',
            field=models.FloatField(default=40.0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='mount_cr',
            field=models.FloatField(default=0),
        ),
    ]
