# Generated by Django 3.2.13 on 2022-06-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoney', '0003_alter_transactions_mount_cr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='trans_id',
        ),
    ]
