# Generated by Django 3.2.13 on 2022-06-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoney', '0006_auto_20220623_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='fuel',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='liters',
            field=models.FloatField(default=0),
        ),
    ]
