# Generated by Django 3.2.13 on 2022-06-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoney', '0005_alter_transactions_cripto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cripto_id',
            field=models.CharField(default=0, max_length=1024),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='exchange',
            field=models.FloatField(default=0),
        ),
    ]
