# Generated by Django 3.2.13 on 2022-06-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=400)),
                ('created_gs', models.DateTimeField(auto_now=True)),
                ('updated_gs', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('wallet_id', models.CharField(max_length=400)),
                ('wallet_name', models.CharField(max_length=45)),
                ('created_pump', models.DateTimeField(auto_now=True)),
                ('updated_pump', models.DateTimeField(auto_now_add=True)),
                ('gas_st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoney.gasstations')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.IntegerField(default=0)),
                ('cripto_id', models.CharField(max_length=1024)),
                ('amount_uy', models.FloatField(default=0)),
                ('exchange', models.FloatField(default=0)),
                ('amount_cr', models.FloatField(default=0)),
                ('fee_cr', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created_tr', models.DateTimeField(auto_now=True)),
                ('updated_tr', models.DateTimeField(auto_now_add=True)),
                ('pump_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoney.pump')),
            ],
        ),
    ]
