# Generated by Django 3.2.13 on 2022-06-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmoney', '0004_remove_transactions_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cripto_id',
            field=models.CharField(default='db17804c37bab1e19aea68500f90938fef0bba83f80a3fb9853ff60d55e6cf54', max_length=1024),
        ),
    ]
